name: Deploy memos

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:admin

      - name: Copy Docker Compose file to host:/home/diego/memos
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ vars.HOSTNAME }} 'mkdir -p ${{ vars.BASE_LOCATION }}/memos && chown ${{ vars.USER }}:${{ vars.GROUP }} ${{ vars.BASE_LOCATION }}/memos'
          scp -o StrictHostKeyChecking=no ./memos.yml root@${{ vars.HOSTNAME }}:${{ vars.BASE_LOCATION }}/memos/

      - name: Run docker compose on host
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.USER }}@${{ vars.HOSTNAME }} 'cd ${{ vars.BASE_LOCATION }}/memos && docker compose -f memos.yml up -d'
