name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:admin
      
      - name: Create user 'diego' and testing_dir on polarbear
        run: |
          ssh -o StrictHostKeyChecking=no diego@polarbear 'bash -s' <<'EOF'
            # Ensure group and user exist
            if ! id -u diego >/dev/null 2>&1; then
              groupadd -f diego
              useradd -m -g diego diego
            fi

            # Create the directory and set ownership
            mkdir -p /home/diego/testing_dir
            chown diego:diego /home/diego/testing_dir
          EOF
