name: CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      
      - name: Ensure user and group 'diego' exist
        run: |
          if ! id -u diego >/dev/null 2>&1; then
            sudo groupadd -f diego
            sudo useradd -m -g diego diego
          fi

      - name: Create testing_dir owned by diego
        run: |
          sudo mkdir -p /home/diego/testing_dir
          sudo chown diego:diego /home/diego/testing_dir
